export const types = {
  SIGN_UP:"SIGN_UP"  ,
  SIGN_UP_SUCCESS:"SIGN_UP_SUCCESS",
  SIGN_UP_FAILED:"SIGN_UP_FAILED",
  
  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILED:"LOGIN_USER_FAILED"
}
